#!/bin/bash

#PBS -P SIHnextgen 
#PBS -l select=1:ncpus=2:mem=32gb:ngpus=1
#PBS -l walltime=1:00:00
#PBS -N exec01

module load singularity

# Assuming you are running this from your project folder, /project/<YOUR_PROJECT>
cd $PBS_O_WORKDIR

### 1 BUILD IMAGE ###
# If these are not set, it defaults to your home foler which will fill up very quickly.
export SINGULARITY_CACHEDIR=`pwd`
export SINGULARITY_TMPDIR=`pwd`

# For example
singularity run --bind /project:/project cryoem.img /bin/bash -c "Gautomatch"
# singularity run --bind /project:/project cryoem.img /bin/bash -c "chimera.bin"

# singularity run --nv -B /dev/dri:/dev/dri -B /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -e QT_X11_NO_MITSHM=1 cryoem.img

#The following paths have been installed in the container
# /opt/miniconda3/bin
# /opt/Gautomatch_v0.53/bin
# /opt/relion/build/bin
# /opt/bin

